version: 2

jobs:

  build:
    docker:
      - image: circleci/clojure:lein-2.8.1

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}


  test:
    docker:
      - image: circleci/clojure:lein-2.8.1

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
      
      - run: lein test


  push-master:
    docker:
      - image: circleci/clojure:lein-2.8.1

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}

      - setup_remote_docker

      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build uberjar
          command: lein uberjar

      - run:
          name: Build Docker Container
          command: docker build -t vadyalex/ordnerd:master .

      - run:
          name: Push to Docker Hub
          command: docker push vadyalex/ordnerd:master

#      -  add_ssh_keys
#
#      - run:
#          name: Deploy
#          command: |
#            ssh-keyscan ${DEPLOY_HOST} 2>/dev/null >> ~/.ssh/known_hosts
#            ssh ${DEPLOY_USER}@${DEPLOY_HOST} "bash -s" < .circleci/deploy.sh master ${TELEGRAM_WEBHOOK} ${TELEGRAM_TOKEN}


  push-release-deploy:
    docker:
      - image: circleci/clojure:lein-2.8.1

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}

      - setup_remote_docker

      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build uberjar
          command: lein uberjar

      - run:
          name: Build Docker Container
          command: docker build -t vadyalex/ordnerd:${CIRCLE_TAG} .

      - run:
          name: Tag latest
          command: docker tag vadyalex/ordnerd:${CIRCLE_TAG} vadyalex/ordnerd:latest

      - run:
          name: Tag master
          command: docker tag vadyalex/ordnerd:${CIRCLE_TAG} vadyalex/ordnerd:master

      - run:
          name: Push to Docker Hub
          command: |
            docker push vadyalex/ordnerd:${CIRCLE_TAG}
            docker push vadyalex/ordnerd:master
            docker push vadyalex/ordnerd:latest

      -  add_ssh_keys

      - run:
          name: Deploy
          command: |
            ssh-keyscan ${DEPLOY_HOST} 2>/dev/null >> ~/.ssh/known_hosts
            ssh ${DEPLOY_USER}@${DEPLOY_HOST} "bash -s" < .circleci/deploy.sh ${CIRCLE_TAG} ${TELEGRAM_WEBHOOK} ${TELEGRAM_TOKEN}


workflows:
  version: 2
  build_test_push_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
      - push-master:
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      - push-release-deploy:
          requires:
            - test
          filters:
            tags:
              only: /v?[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/